// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChallengerMock is an autogenerated mock type for the ChallengerMock type
type ChallengerMock struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *ChallengerMock) Generate() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify provides a mock function with given fields: _a0, _a1
func (_m *ChallengerMock) Verify(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewChallengerMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewChallengerMock creates a new instance of ChallengerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChallengerMock(t mockConstructorTestingTNewChallengerMock) *ChallengerMock {
	mock := &ChallengerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
